[2025-06-18T13:48:13.479+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T13:48:13.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lakehouse_ingest_pipeline.produce_csv_to_kafka manual__2025-06-18T13:47:45.927509+00:00 [queued]>
[2025-06-18T13:48:13.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lakehouse_ingest_pipeline.produce_csv_to_kafka manual__2025-06-18T13:47:45.927509+00:00 [queued]>
[2025-06-18T13:48:13.521+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-06-18T13:48:13.533+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): produce_csv_to_kafka> on 2025-06-18 13:47:45.927509+00:00
[2025-06-18T13:48:13.538+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=215) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-18T13:48:13.541+0000] {standard_task_runner.py:63} INFO - Started process 216 to run task
[2025-06-18T13:48:13.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lakehouse_ingest_pipeline', 'produce_csv_to_kafka', 'manual__2025-06-18T13:47:45.927509+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/lakehouse_ingest_pipeline.py', '--cfg-path', '/tmp/tmp_4m590_5']
[2025-06-18T13:48:13.544+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask produce_csv_to_kafka
[2025-06-18T13:48:13.557+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-18T13:48:13.595+0000] {task_command.py:426} INFO - Running <TaskInstance: lakehouse_ingest_pipeline.produce_csv_to_kafka manual__2025-06-18T13:47:45.927509+00:00 [running]> on host 60d953cfa512
[2025-06-18T13:48:13.672+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lakehouse_ingest_pipeline' AIRFLOW_CTX_TASK_ID='produce_csv_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T13:47:45.927509+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T13:47:45.927509+00:00'
[2025-06-18T13:48:13.674+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T13:48:13.697+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-18T13:48:13.699+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/tools/produce_csv_to_kafka.py --bootstrap-server kafka:9092 --topic footware_sales --file /opt/***/data/FootWare_Sales_Dataset/FootWare_Wholesale_Sales_Dataset.csv']
[2025-06-18T13:48:13.710+0000] {subprocess.py:86} INFO - Output:
[2025-06-18T13:48:16.410+0000] {subprocess.py:93} INFO - ▶️  Khởi tạo KafkaProducer…
[2025-06-18T13:48:16.411+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-18T13:48:16.412+0000] {subprocess.py:93} INFO -   File "/opt/***/tools/produce_csv_to_kafka.py", line 10, in <module>
[2025-06-18T13:48:16.414+0000] {subprocess.py:93} INFO -     producer = KafkaProducer(
[2025-06-18T13:48:16.415+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^
[2025-06-18T13:48:16.416+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 481, in __init__
[2025-06-18T13:48:16.417+0000] {subprocess.py:93} INFO -     client = self.config['kafka_client'](
[2025-06-18T13:48:16.418+0000] {subprocess.py:93} INFO -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-18T13:48:16.419+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
[2025-06-18T13:48:16.419+0000] {subprocess.py:93} INFO -     self.config['api_version'] = self.check_version()
[2025-06-18T13:48:16.420+0000] {subprocess.py:93} INFO -                                  ^^^^^^^^^^^^^^^^^^^^
[2025-06-18T13:48:16.420+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1074, in check_version
[2025-06-18T13:48:16.421+0000] {subprocess.py:93} INFO -     raise Errors.NoBrokersAvailable()
[2025-06-18T13:48:16.421+0000] {subprocess.py:93} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-06-18T13:48:16.457+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-18T13:48:16.458+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T13:48:16.471+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-18T13:48:16.475+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=lakehouse_ingest_pipeline, task_id=produce_csv_to_kafka, run_id=manual__2025-06-18T13:47:45.927509+00:00, execution_date=20250618T134745, start_date=20250618T134813, end_date=20250618T134816
[2025-06-18T13:48:16.485+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task produce_csv_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 216)
[2025-06-18T13:48:16.492+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T13:48:16.513+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T13:48:16.515+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
